function [x,idx1,idx2] = x_transform(x,xlim,gap_size)
idx1 = x <= xlim(1,2);
idx2 = x >= xlim(2,1);
w = (1-gap_size)/2;
x = [ ...
    (x(idx1)-xlim(1,1))/(xlim(1,2)-xlim(1,1))*w NaN ...
    (x(idx2)-xlim(2,1))/(xlim(2,2)-xlim(2,1))*w+1-w ...
    ];
end