function [Ns_Config,Nc_Config,Js_RNA,Js_DNA,Js_Sites,linearIndexed,MultiDim_PJSMC,MultiDim_PJSMTDC] = A_ModelSolverWrapper_V4(probes,Pset,settings,DoesProbeBindSite,DNA_IDs,NonDNA_IDs,dCp_mod,dHeq_mod,dSeq_mod,dCp_Complement,dSeq_Complement,dHeq_Complement)
    R = 0.001987204259;%gas constant [Energy Kcal/mol K
    kb = 1.380649*10^-23;%bolzman constant J/K
    h = 6.62607015*10^-34;%planks constant J/Hz
    Tref = 37+273.15;   
    spfunction = @(x) sqrt(x+1)-1;     
    Js = @(x) find(sum(squeeze(sum(DoesProbeBindSite(x,:,:),1)),2)>0);
    Js_Sites = @(x) find(sum(sum(DoesProbeBindSite(x,Js(x),:),1),2)>0);
    Js_DNA = @(x)DNA_IDs(ismember(DNA_IDs,Js(x)));
    Js_RNA = @(x)NonDNA_IDs(ismember(NonDNA_IDs,Js(x))); 
    DoesProbeBindTarget = ndSparse(double(sum(DoesProbeBindSite,3)>0));
    DoesTargetHaveSite = ndSparse(double(sum(DoesProbeBindSite,1)>0));
    [SelfSeqParsed,CrossDimerSeqParsed] = A_JH_GenerateSecondaryStructureSeq(probes,Pset,settings);
    crossNotExist = cellfun(@isempty,CrossDimerSeqParsed);
    selfNotExist = cellfun(@isempty,SelfSeqParsed);
    [crossId1,crossId2] = find(crossNotExist==1);
    selfId1 = find(selfNotExist==1);
    for i = 1:length(selfId1)
       SelfSeqParsed{selfId1(i)}=cell(0,2); 
    end
    for i = 1:length(crossId1)
        CrossDimerSeqParsed{crossId1(i),crossId2(i)}=cell(0,2);
    end
    CrossDimerSeqParsed = cellfun(@(x) x(sum(cellfun(@isempty,x),2)'==0,1:2), CrossDimerSeqParsed,'Un',0);
    Ns = cellfun(@(x) length(x), SelfSeqParsed);
    Nc = cellfun(@(x) size(x,1), CrossDimerSeqParsed);
    Ns_val = zeros(size(probes,1),max(Ns(:)));
    Nc_val = zeros(size(probes,1),size(probes,1),max(Nc(:)));
    for i=1:length(Pset)
        if (Ns(i)>0)
            Ns_val(Pset(i),1:Ns(i)) = 1; 
        end
        for j = 1:length(Pset)
                if (Nc(i,j)>0)
                    Nc_val(Pset(i),Pset(j),1:Nc(i,j)) = 1; 
                end
        end
    end
    Ns_Config = size(Ns_val,2);
    Nc_Config = size(Nc_val,3);
    c_alpha = ones(size(probes,1))+diag(diag(ones(size(probes,1))));
    [~,dHs_eq,dSs_eq,~,~,~,~,...
    dCps_eq,~,dHd_eq,dSd_eq,~,~,~,~,dCpd_eq,~,~] = A_JH_GenerateSecondaryStructureInfo_V2(probes,Pset,settings); 
    %probe,config,model,temp,dilution,cellline
    DHs_eq_sc = @(T,Tref,p,n,m) dHs_eq(p,n,m) + dCps_eq(p,n,m)*(T-Tref);
    DHs_eq = @(T,Tref,p,n,m) dHs_eq(p,n,m) + dCps_eq(p,n,m)*(T-Tref);
    DSs_eq_sc = @(T,Tref,p,n,m) dSs_eq(p,n,m) + dCps_eq(p,n,m)*log(T/Tref);
    DSs_eq = @(T,Tref,p,n,m) repmat(dSs_eq(p,n,m),[1 1 1 length(T)]) + ...
        repmat(dCps_eq(p,n,m),[1 1 1 length(T)]).*...
        permute(repmat(log(T'/Tref),[1 length(p) length(n) length(m)]),[2 3 4 1]);
    Ks_eq_sc = @(T,Tref,p,n,m) repmat(Ns_val(p,n),[1 1 length(m)]).*spfun(@exp,-DHs_eq_sc(T,Tref,p,n,m)/(R*T)+DSs_eq_sc(T,Tref,p,n,m)/R);
    Ks_eq = @(T,Tref,p,n,m) repmat(Ns_val(p,n),[1 1 length(m) length(T)]).*...
        spfun(@exp,-DHs_eq(T,Tref,p,n,m)./...
        permute(repmat(R*T',[1 length(p) length(n) length(m)]),[2 3 4 1])+...
        DSs_eq(T,Tref,p,n,m)/R);
    K_S_sc = @(T,Tref,p,n,m,c) repmat(squeeze(sum(Ks_eq_sc(T,Tref,p,n,m),2)),[1 1 length(c)]);
    K_S = @(T,Tref,p,n,m,d,c) repmat(squeeze(sum(Ks_eq(T,Tref,p,n,m),2)),[1 1 1 length(d) length(c)]);
    %probe,probe,config,model,temp
    DHd_eq_sc = @(T,Tref,p,q,n,m) dHd_eq(p,q,n,m) + dCpd_eq(p,q,n,m)*(T-Tref);
    DHd_eq = @(T,Tref,p,q,n,m) repmat(dHd_eq(p,q,n,m),[1 1 1 1 length(T)]) + ...
                               repmat(dCpd_eq(p,q,n,m),[1 1 1 1 length(T)]).*...
                               permute(repmat(T'-Tref,[1 length(p) length(q) length(n) length(m)]),[2 3 4 5 1]);                    
    DSd_eq_sc = @(T,Tref,p,q,n,m) dSd_eq(p,q,n,m)+dCpd_eq (p,q,n,m)*log(T/Tref);  
    DSd_eq = @(T,Tref,p,q,n,m) repmat(dSd_eq(p,q,n,m),[1 1 1 1 length(T)]) + ...
                               repmat(dCpd_eq (p,q,n,m),[1 1 1 1 length(T)]).*...
                               permute(repmat(log(T'/Tref),[1 length(p) length(q) length(n) length(m)]),[2 3 4 5 1]);  
    Kd_eq_sc = @(T,Tref,p,q,n,m) repmat(Nc_val(p,q,n),[1 1 1 length(m)]).*repmat(c_alpha(p,q),[1 1 length(n) length(m)]).*spfun(@exp,-DHd_eq_sc(T,Tref,p,q,n,m)./(R*T)+DSd_eq_sc(T,Tref,p,q,n,m)/R);    
    Kd_eq = @(T,Tref,p,q,n,m) repmat(Nc_val(p,q,n),[1 1 1 length(m) length(T)]).*...
                              repmat(c_alpha(p,q),[1 1 length(n) length(m) length(T)]).*...
                              spfun(@exp,-DHd_eq(T,Tref,p,q,n,m)./...
                              permute(repmat(R*T',[1 length(p) length(q) length(n) length(m)]),[2 3 4 5 1])+...
                              DSd_eq(T,Tref,p,q,n,m)/R); 
    %probe,model,temp,dilution,cell-line
    K_CDeff_lind = @(pf,T,Tref,p,q,n,m,c) sum(repmat(squeeze(sum(Kd_eq_sc(T,Tref,p,q,n,m),3)),[1 1 1 length(c)]).*repmat(pagetranspose(sum(permute(repmat(pf,[ones(1,length(size(pf))) 2]),[1 1+length(size(pf)) 2:length(size(pf))]),2)/2),[length(p) 1 1 1]),2);           
    K_CDeff_sc = @(pf,T,Tref,p,q,n,m,c) multiprod(repmat(sum(Kd_eq_sc(T,Tref,p,q,n,m),3),[1 1 1 1 length(c)]),sum(permute(repmat(pf,[ones(1,length(size(pf))) 2]),[1 1+length(size(pf)) 2:length(size(pf))]),2)/2);                
    K_CDeff = @(pf,T,Tref,p,q,n,m,d,c) multiprod(repmat(squeeze(sum(Kd_eq(T,Tref,p,q,n,m),3)),[1 1 1 1 length(d) length(c)]),sum(permute(repmat(pf,[ones(1,length(size(pf))) 2]),[1 1+length(size(pf)) 2:length(size(pf))]),2)/2);                
    
    %probe,target,site,model,temp
    DHeq_mod_lind = @(T,Tref,p,qrlist_paired,m) CATnWrapper(arrayfun(@(y) CATnWrapper(arrayfun(@(x) ...
        dHeq_mod(sub2ind(size(dHeq_mod),x*ones(size(qrlist_paired(1,:))),qrlist_paired(1,:),qrlist_paired(2,:),y*ones(size(qrlist_paired(2,:))))) + ...
        dCp_mod(sub2ind(size(dCp_mod),x*ones(size(qrlist_paired(1,:))),qrlist_paired(1,:),qrlist_paired(2,:),y*ones(size(qrlist_paired(2,:)))))*(T-Tref),p,'Un',0),1),m,'Un',0),3);
    DHeq_mod_sc = @(T,Tref,p,q,r,m) dHeq_mod(p,q,r,m)+ dCp_mod(p,q,r,m)*(T-Tref);
    DHeq_mod = @(T,Tref,p,q,r,m) repmat(dHeq_mod(p,q,r,m),[1 1 1 1 length(T)]) + ...
        repmat(dCp_mod(p,q,r,m),[1 1 1 1 length(T)]).*...
        permute(repmat(T'-Tref,[1 length(p) length(q) length(r) length(m)]),[2 3 4 5 1]);

    DSeq_mod_lind = @(T,Tref,p,qrlist_paired,m) CATnWrapper(arrayfun(@(y) CATnWrapper(arrayfun(@(x) ...
        dSeq_mod(sub2ind(size(dSeq_mod),x*ones(size(qrlist_paired(1,:))),qrlist_paired(1,:),qrlist_paired(2,:),y*ones(size(qrlist_paired(2,:))))) + ...
        dCp_mod(sub2ind(size(dCp_mod),x*ones(size(qrlist_paired(1,:))),qrlist_paired(1,:),qrlist_paired(2,:),y*ones(size(qrlist_paired(2,:)))))*log(T/Tref),p,'Un',0),1),m,'Un',0),3);
    DSeq_mod_sc = @(T,Tref,p,q,r,m) dSeq_mod(p,q,r,m) + dCp_mod(p,q,r,m)*log(T/Tref);
    DSeq_mod = @(T,Tref,p,q,r,m) repmat(dSeq_mod(p,q,r,m),[1 1 1 1 length(T)]) + ...
        repmat(dCp_mod(p,q,r,m),[1 1 1 1 length(T)]).*...
        permute(repmat(log(T'/Tref),[1 length(p) length(q) length(r) length(m)]),[2 3 4 5 1]);

    Keq_mod_lind = @(T,Tref,p,qrlist_paired,m) CATnWrapper(arrayfun(@(x) ...
        DoesProbeBindSite(sub2ind(size(DoesProbeBindSite),x*ones(size(qrlist_paired(1,:))),qrlist_paired(1,:),qrlist_paired(2,:))),p,'Un',0),1).*...
        spfun(@exp,-DHeq_mod_lind(T,Tref,p,qrlist_paired,m)/(R*T)+ DSeq_mod_lind(T,Tref,p,qrlist_paired,m)/R);
    Keq_mod_sc = @(T,Tref,p,q,r,m) DoesProbeBindSite(p,q,r).*spfun(@exp,-DHeq_mod_sc(T,Tref,p,q,r,m)./(R*T)+ DSeq_mod_sc(T,Tref,p,q,r,m)/R);
    Keq_mod = @(T,Tref,p,q,r,m) repmat(DoesProbeBindSite(p,q,r),[1 1 1 length(m) length(T)]).*...
        spfun(@exp,-DHeq_mod(T,Tref,p,q,r,m)./...
        permute(repmat(R*T',[1 length(p) length(q) length(r) length(m)]),[2 3 4 5 1])...
        + DSeq_mod(T,Tref,p,q,r,m)/R);
    %target,site,model,temp 
    
    DHeq_Complement_lind = @(T,Tref,p,qrlist_paired,m) CATnWrapper(arrayfun(@(y) dHeq_Complement(sub2ind(size(dHeq_Complement),qrlist_paired(1,:),qrlist_paired(2,:),y*ones(size(qrlist_paired(2,:)))))+ ...
        dCp_Complement(sub2ind(size(dCp_Complement),qrlist_paired(1,:),qrlist_paired(2,:),y*ones(size(qrlist_paired(2,:)))))*(T-Tref),m,'Un',0),1)';
    DHeq_Complement_sc = @(T,Tref,q,r,m) dHeq_Complement(q,r,m) + dCp_Complement(q,r,m)*(T-Tref);
    DHeq_Complement = @(T,Tref,q,r,m) repmat(dHeq_Complement(q,r,m),[1 1 1 length(T)]) + ...
        repmat(dCp_Complement(q,r,m),[1 1 1 length(T)]).*...
        permute(repmat(T'-Tref,[1 length(q) length(r) length(m)]),[2 3 4 1]);
    
    DSeq_Complement_lind = @(T,Tref,p,qrlist_paired,m) CATnWrapper(arrayfun(@(y) dSeq_Complement(sub2ind(size(dSeq_Complement),qrlist_paired(1,:),qrlist_paired(2,:),y*ones(size(qrlist_paired(2,:)))))+ ...
        dCp_Complement(sub2ind(size(dCp_Complement),qrlist_paired(1,:),qrlist_paired(2,:),y*ones(size(qrlist_paired(2,:)))))*log(T/Tref),m,'Un',0),1)';
    DSeq_Complement_sc = @(T,Tref,q,r,m) dSeq_Complement(q,r,m) + dCp_Complement(q,r,m).*log(T/Tref);                             
    DSeq_Complement = @(T,Tref,q,r,m) repmat(dSeq_Complement(q,r,m),[1 1 1 length(T)]) + ...
                                 repmat(dCp_Complement(q,r,m),[1 1 1 length(T)]).*...
                                 permute(repmat(log(T'/Tref),[1 length(q) length(r) length(m)]),[2 3 4 1]);  

    Keq_Complement_lind = @(T,Tref,p,qrlist_paired,m) DoesTargetHaveSite(sub2ind(size(DoesTargetHaveSite),qrlist_paired(1,:),qrlist_paired(2,:)))'.*...
        spfun(@exp,-DHeq_Complement_lind(T,Tref,p,qrlist_paired,m)/(R*T)+ DSeq_Complement_lind(T,Tref,p,qrlist_paired,m)/R);
    Keq_Complement_sc = @(T,Tref,q,r,m) repmat(DoesTargetHaveSite(q,r),[1 1 length(m)]).*spfun(@exp,-DHeq_Complement_sc(T,Tref,q,r,m)./(R*T)+ DSeq_Complement_sc(T,Tref,q,r,m)/R);  
    Keq_Complement = @(T,Tref,q,r,m) repmat(DoesTargetHaveSite(q,r),[1 1 length(m) length(T)]).*...
                                spfun(@exp,-DHeq_Complement(T,Tref,q,r,m)./...
                                permute(repmat(R*T',[1 length(q) length(r) length(m)]),[2 3 4 1])...
                                + DSeq_Complement(T,Tref,q,r,m)/R);     
    
    sub_base_lind = @(pf,T,Tref,p,qrlist_paired,m,c) sum(repmat(Keq_mod_lind(T,Tref,p,qrlist_paired,m),[1 1 1 length(c)]).*permute(repmat(pf,[1 1 1 length(qrlist_paired(1,:))]),[1 4 2 3]),1);
    sub_base_sc = @(pf,T,Tref,p,q,r,m,c) sum(repmat(Keq_mod_sc(T,Tref,p,q,r,m),[1 1 1 1 length(c)]).*permute(repmat(pf,[1 1 1 length(q) length(r)]),[1 4 5 2 3]),1);
    sub_base = @(pf,T,Tref,p,q,r,m,d,c) sum(repmat(Keq_mod(T,Tref,p,q,r,m),[1 1 1 1 1 length(d) length(c)]).*...
                                         permute(repmat(pf,[1 1 1 1 1 length(q) length(r)]),[1 6 7 2 3 4 5]),1);% [1 x N_Targets x N_sites x N_Models x N_Temperatures x N_Dilutions x N_CellLines]
    
    sub_RNA_lind = @(pf,T,Tref,p,qrlist_paired,m,c,cExpressionMatrix) permute(repmat(cExpressionMatrix(qrlist_paired(1,:),c),[1 1 length(p) length(m)]),[3 1 4 2])./ndSparse(1+sub_base_lind(pf,T,Tref,p,qrlist_paired,m,c));
    sub_RNA_sc = @(pf,T,Tref,p,q,r,m,c,cExpressionMatrix) permute(repmat(cExpressionMatrix(q,c),[1 1 length(p) length(r) length(m)]),[3 1 4 5 2])./ndSparse(1+sub_base_sc(pf,T,Tref,p,q,r,m,c));
    sub_RNA = @(pf,T,Tref,p,q,r,m,d,c,cExpressionMatrix) permute(repmat(cExpressionMatrix(q,c),[1 1 length(p) length(r) length(m) length(T) length(d)]),...
                                        [3 1 4 5 6 7 2])./permute(repmat(permute(ndSparse(1+sub_base(pf,T,Tref,p,q,r,m,d,c)),[2 3 4 5 6 7 1]),[1 1 1 1 1 1 length(p)]),[7 1 2 3 4 5 6]);                                 
    
    sub_DNA_lind = @(pf,T,Tref,p,qrlist_paired,m,c,cExpressionMatrix) 2*spfun(spfunction, 4*permute(repmat(cExpressionMatrix(qrlist_paired(1,:),c),[1 1 length(p) length(m)]),[3 1 4 2]).*...
        permute(repmat(Keq_Complement_lind(T,Tref,p,qrlist_paired,m),[1 1 length(p) length(c)]),[3 1 2 4])./ndSparse(1+sub_base_lind(pf,T,Tref,p,qrlist_paired,m,c)))./...
        permute(repmat(Keq_Complement_lind(T,Tref,p,qrlist_paired,m),[1 1 length(p) length(c)]),[3 1 2 4]);
    sub_DNA_sc = @(pf,T,Tref,p,q,r,m,c,cExpressionMatrix) 2*spfun(spfunction,4*permute(repmat(cExpressionMatrix(q,c),[1 1 length(p) length(r) length(m)]),[3 1 4 5 2]).*...
        permute(repmat(Keq_Complement_sc(T,Tref,q,r,m),[1 1 1 length(p) length(c)]),[4 1 2 3 5])./ndSparse(1+sub_base_sc(pf,T,Tref,p,q,r,m,c)))./permute(repmat(Keq_Complement_sc(T,Tref,q,r,m),[1 1 1 length(p) length(c)]),[4 1 2 3 5]);
    sub_DNA = @(pf,T,Tref,p,q,r,m,d,c,cExpressionMatrix) 2*spfun(spfunction,...
           4*permute(repmat(cExpressionMatrix(q,c),[1 1 length(p) length(r) length(m) length(T) length(d)]),[3 1 4 5 6 7 2]).*...
           permute(repmat(Keq_Complement(T,Tref,q,r,m),[1 1 1 1 length(p) length(d) length(c)]),[5 1 2 3 4 6 7])./...
           ndSparse(1+sub_base(pf,T,Tref,p,q,r,m,d,c)))./permute(repmat(Keq_Complement(T,Tref,q,r,m),[1 1 1 1 length(p) length(d) length(c)]),[5 1 2 3 4 6 7]);
    
    sub_DNA_Complement_lind= @(pf,T,Tref,p,qrlist_paired,m,c,cExpressionMatrix) permute(repmat(cExpressionMatrix(qrlist_paired(1,:),c),[1 1 length(p) length(m)]),[3 1 4 2])./...
        ndSparse(1+sub_DNA_lind(pf,T,Tref,p,qrlist_paired,m,c,cExpressionMatrix)).*...
        permute(repmat(Keq_Complement_lind(T,Tref,p,qrlist_paired,m),[1 1 length(p) length(c)]),[3 1 2 4]);
    sub_DNA_Complement_sc = @(pf,T,Tref,p,q,r,m,c,cExpressionMatrix) permute(repmat(cExpressionMatrix(q,c),[1 1 length(p) length(r) length(m)]),[3 1 4 5 2])./...
        ndSparse(1+sub_DNA_sc(pf,T,Tref,p,q,r,m,c,cExpressionMatrix)).*permute(repmat(Keq_Complement_sc(T,Tref,q,r,m),[1 1 1 length(p) length(c)]),[4 1 2 3 5]);
    sub_DNA_Complement = @(pf,T,Tref,p,q,r,m,d,c,cExpressionMatrix) permute(repmat(cExpressionMatrix(q,c),[1 1 length(p) length(r) length(m) length(T) length(d)]),...
        [3 1 4 5 6 7 2])./ndSparse(1+sub_DNA(pf,T,Tref,p,q,r,m,d,c,cExpressionMatrix).*permute(repmat(Keq_Complement(T,Tref,q,r,m),[1 1 1 1 length(p) length(d) length(c)]),[5 1 2 3 4 6 7]));
    
       h_RNA_lind = @(pf,T,Tref,p,qrlist_paired,m,c,cExpressionMatrix)  sum(repmat(Keq_mod_lind(T,Tref,p,qrlist_paired,m),[1 1 1 length(c)]).*...
            sub_RNA_lind(pf,T,Tref,p,qrlist_paired,m,c,cExpressionMatrix),2,'omitnan'); 
       h_RNA_sc = @(pf,T,Tref,p,q,r,m,c,cExpressionMatrix)  sum(sum(repmat(Keq_mod_sc(T,Tref,p,q,r,m),[1 1 1 1 length(c)]).*...
           sub_RNA_sc(pf,T,Tref,p,q,r,m,c,cExpressionMatrix),2,'omitnan'),3,'omitnan');
       h_RNA = @(pf,T,Tref,p,q,r,m,d,c,cExpressionMatrix)  sum(sum(repmat(Keq_mod(T,Tref,p,q,r,m),[1 1 1 1 1 length(d) length(c)]).*...
           sub_RNA(pf,T,Tref,p,q,r,m,d,c,cExpressionMatrix),2,'omitnan'),3,'omitnan');
    
       h_DNA_lind = @(pf,T,Tref,p,qrlist_paired,m,c,cExpressionMatrix)  sum(repmat(Keq_mod_lind(T,Tref,p,qrlist_paired,m),[1 1 1 length(c)]).*...
            sub_DNA_lind(pf,T,Tref,p,qrlist_paired,m,c,cExpressionMatrix),2,'omitnan'); 
       h_DNA_sc = @(pf,T,Tref,p,q,r,m,c,cExpressionMatrix)  sum(sum(repmat(Keq_mod_sc(T,Tref,p,q,r,m),[1 1 1 1 length(c)]).*...
           sub_DNA_sc(pf,T,Tref,p,q,r,m,c,cExpressionMatrix),2,'omitnan'),3,'omitnan');
       h_DNA = @(pf,T,Tref,p,q,r,m,d,c,cExpressionMatrix)  sum(sum(repmat(Keq_mod(T,Tref,p,q,r,m),[1 1 1 1 1 length(d) length(c)]).*...
           sub_DNA(pf,T,Tref,p,q,r,m,d,c,cExpressionMatrix),2,'omitnan'),3,'omitnan');
    %t = temperature
    %p = probe
    %q = target
    %r = site
    %m = model   
    Target_List_RNA = Js_RNA(Pset);
    Target_List_DNA = Js_DNA(Pset);
    Sites_List = Js_Sites(Pset);
    [~,tList_RNA,sList_RNA] = ind2sub(size(DoesProbeBindSite(Pset,Target_List_RNA,Sites_List)),find(DoesProbeBindSite(Pset,Target_List_RNA,Sites_List)));
    [~,tList_DNA,sList_DNA] = ind2sub(size(DoesProbeBindSite(Pset,Target_List_DNA,Sites_List)),find(DoesProbeBindSite(Pset,Target_List_DNA,Sites_List)));
    tList_RNA = Target_List_RNA(tList_RNA);
    sList_RNA = Sites_List(sList_RNA);
    tsList_RNA = unique([tList_RNA; sList_RNA]','rows','stable')';
    tList_DNA = Target_List_DNA(tList_DNA);
    sList_DNA = Sites_List(sList_DNA);
    tsList_DNA = unique([tList_DNA; sList_DNA]','rows','stable')';

    linearIndexed = struct();
    MultiDim_PJSMC = struct();
    MultiDim_PJSMTDC = struct();
    linearIndexed.solverType=0;
    MultiDim_PJSMC.solverType=1;
    MultiDim_PJSMTDC.solverType=2;
    linearIndexed.Paired_RNATargetSites = tsList_RNA;
    linearIndexed.Paired_DNATargetSites = tsList_DNA;

    linearIndexed.K_S = K_S_sc;
    MultiDim_PJSMC.K_S = K_S_sc;
    MultiDim_PJSMTDC.K_S = K_S;
    linearIndexed.K_CDeff = K_CDeff_lind;
    MultiDim_PJSMC.K_CDeff  = K_CDeff_sc;
    MultiDim_PJSMTDC.K_CDeff = K_CDeff;
    linearIndexed.h_RNA = h_RNA_lind;
    MultiDim_PJSMC.h_RNA = h_RNA_sc;
    MultiDim_PJSMTDC.h_RNA = h_RNA;
    linearIndexed.h_DNA = h_DNA_lind;
    MultiDim_PJSMC.h_DNA = h_DNA_sc;
    MultiDim_PJSMTDC.h_DNA = h_DNA;


    linearIndexed.h_DNA = h_DNA_lind;
    MultiDim_PJSMC.h_DNA = h_DNA_sc;
    MultiDim_PJSMTDC.h_DNA = h_DNA;
    linearIndexed.Keq_mod = Keq_mod_lind;
    MultiDim_PJSMC.Keq_mod = Keq_mod_sc;
    MultiDim_PJSMTDC.Keq_mod = Keq_mod;
    linearIndexed.Keq_mod = Keq_mod_lind;
    MultiDim_PJSMC.Keq_mod = Keq_mod_sc;
    MultiDim_PJSMTDC.Keq_mod = Keq_mod;
    linearIndexed.sub_base = sub_base_lind;
    MultiDim_PJSMC.sub_base = sub_base_sc;
    MultiDim_PJSMTDC.sub_base = sub_base;
    linearIndexed.sub_RNA = sub_RNA_lind;
    MultiDim_PJSMC.sub_RNA = sub_RNA_sc;
    MultiDim_PJSMTDC.sub_RNA = sub_RNA;
    linearIndexed.Kd_eq = Kd_eq_sc;
    MultiDim_PJSMC.Kd_eq = Kd_eq_sc;
    MultiDim_PJSMTDC.Kd_eq = Kd_eq_sc;
    linearIndexed.pRNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix) ...
        repmat(Keq_mod_lind(Tvec,Tref,Pset,Paired_TargetSites,Mvec),[1 1 1 length(Cvec)]).*...
        sub_RNA_lind(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Paired_TargetSites(1,:))]),[1 4 2 3])./...    
        (sum(repmat(Keq_mod_lind(Tvec,Tref,Pset,Paired_TargetSites,Mvec),[1 1 1 length(Cvec)]).*...
        sub_RNA_lind(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Paired_TargetSites(1,:))]),[1 4 2 3]),1)+...
        sub_RNA_lind(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix));
 linearIndexed.pDNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix) ...
        repmat(Keq_mod_lind(Tvec,Tref,Pset,Paired_TargetSites,Mvec),[1 1 1 length(Cvec)]).*...
        sub_DNA_lind(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Paired_TargetSites(1,:))]),[1 4 2 3])./...        
        (sum(repmat(Keq_mod_lind(Tvec,Tref,Pset,Paired_TargetSites,Mvec),[1 1 1 length(Cvec)]).*...
        sub_DNA_lind(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Paired_TargetSites(1,:))]),[1 4 2 3]),1)+...
        permute(repmat(Keq_Complement_lind(Tvec,Tref,Pset,Paired_TargetSites,Mvec),[1 1 1 length(Pset)]),[4 1 2 3]).*...
        sub_DNA_lind(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix)+...
        sub_DNA_Complement_lind(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix));

 linearIndexed.cRNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix) ...
        repmat(Keq_mod_lind(Tvec,Tref,Pset,Paired_TargetSites,Mvec),[1 1 1 length(Cvec)]).*...
        sub_RNA_lind(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Paired_TargetSites(1,:))]),[1 4 2 3]);
   linearIndexed.cDNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix) ...
        repmat(Keq_mod_lind(Tvec,Tref,Pset,Paired_TargetSites,Mvec),[1 1 1 length(Cvec)]).*...
        sub_DNA_lind(CProbes_Free,Tvec,Tref,Pset,Paired_TargetSites,Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Paired_TargetSites(1,:))]),[1 4 2 3]);

    MultiDim_PJSMC.pRNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Mvec,Cvec,cExpressionMatrix) ...
        (repmat(Keq_mod_sc(Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 length(Cvec)]).*...
        sub_RNA_sc(CProbes_Free,Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Js_RNA(Pset)) length(Js_Sites(Pset))]),[1 4 5 2 3]))./...    
        (sum(repmat(Keq_mod_sc(Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 length(Cvec)]).*...
        sub_RNA_sc(CProbes_Free,Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Js_RNA(Pset)) length(Js_Sites(Pset))]),[1 4 5 2 3]),1)+...
        sub_RNA_sc(CProbes_Free,Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec,Cvec,cExpressionMatrix));
   MultiDim_PJSMC.pDNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Mvec,Cvec,cExpressionMatrix)...
        repmat(Keq_mod_sc(Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 length(Cvec)]).*...
        sub_DNA_sc(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Js_DNA(Pset)) length(Js_Sites(Pset))]),[1 4 5 2 3])./...
        (sum(repmat(Keq_mod_sc(Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 length(Cvec)]).*...
        sub_DNA_sc(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Js_DNA(Pset)) length(Js_Sites(Pset))]),[1 4 5 2 3]),1)+...
        permute(repmat(Keq_Complement_sc(Tvec,Tref,Js_DNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 length(Pset) length(Cvec)]),[4 1 2 3 5]).*...
        sub_DNA_sc(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Cvec,cExpressionMatrix).*...
        sub_DNA_Complement_sc(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Cvec,cExpressionMatrix)+...
        sub_DNA_sc(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Cvec,cExpressionMatrix));
    MultiDim_PJSMC.cRNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Mvec,Cvec,cExpressionMatrix) ...
        repmat(Keq_mod_sc(Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 length(Cvec)]).*...
        sub_RNA_sc(CProbes_Free,Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Js_RNA(Pset)) length(Js_Sites(Pset))]),[1 4 5 2 3]);
    MultiDim_PJSMC.cDNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Mvec,Cvec,cExpressionMatrix) ...
        repmat(Keq_mod_sc(Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 length(Cvec)]).*...
        sub_DNA_sc(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 length(Js_DNA(Pset)) length(Js_Sites(Pset))]),[1 4 5 2 3]);  
     MultiDim_PJSMTDC.pRNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Mvec,Dvec,Cvec,cExpressionMatrix) ...
        (repmat(Keq_mod(Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 length(Cvec)]).*...
        sub_RNA(CProbes_Free,Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec,Dvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 1 1 length(Js_RNA(Pset)) length(Js_Sites(Pset))]),[1 6 7 2 3 4 5]))./...    
        (sum(repmat(Keq_mod(Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 length(Cvec)]).*...
        sub_RNA(CProbes_Free,Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec,Dvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 1 1 length(Js_RNA(Pset)) length(Js_Sites(Pset))]),[1 6 7 2 3 4 5]),1)+...
        sub_RNA(CProbes_Free,Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec,Dvec,Cvec,cExpressionMatrix));
    MultiDim_PJSMTDC.pDNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Mvec,Dvec,Cvec,cExpressionMatrix)...
        repmat(Keq_mod(Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 1 length(Dvec) length(Cvec)]).*...
        sub_DNA(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Dvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 1 1 length(Js_DNA(Pset)) length(Js_Sites(Pset))]),[1 6 7 2 3 4 5])./...
        (sum(repmat(Keq_mod(Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 1 length(Dvec) length(Cvec)]).*...
        sub_DNA(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Dvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 1 1 length(Js_DNA(Pset)) length(Js_Sites(Pset))]),[1 6 7 2 3 4 5]),1)+...
        permute(repmat(Keq_Complement(Tvec,Tref,Js_DNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 length(Pset) length(Dvec) length(Cvec)]),[5 1 2 3 4 6 7]).*...
        sub_DNA(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Dvec,Cvec,cExpressionMatrix).*...
        sub_DNA_Complement(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Dvec,Cvec,cExpressionMatrix)+...
        sub_DNA(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Dvec,Cvec,cExpressionMatrix));
     MultiDim_PJSMTDC.cRNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Mvec,Dvec,Cvec,cExpressionMatrix) ...
        repmat(Keq_mod(Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 1 length(Dvec) length(Cvec)]).*...
        sub_RNA(CProbes_Free,Tvec,Tref,Pset,Js_RNA(Pset),Js_Sites(Pset),Mvec,Dvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 1 1 length(Js_RNA(Pset)) length(Js_Sites(Pset))]),[1 6 7 2 3 4 5]);
     MultiDim_PJSMTDC.cDNA_TargetSites_Bound_Func = @(CProbes_Free,Tvec,Tref,Pset,Mvec,Dvec,Cvec,cExpressionMatrix) ...
        repmat(Keq_mod(Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec),[1 1 1 1 1 length(Dvec) length(Cvec)]).*...
        sub_DNA(CProbes_Free,Tvec,Tref,Pset,Js_DNA(Pset),Js_Sites(Pset),Mvec,Dvec,Cvec,cExpressionMatrix).*...
        permute(repmat(CProbes_Free,[1 1 1 1 1 length(Js_DNA(Pset)) length(Js_Sites(Pset))]),[1 6 7 2 3 4 5]);  
end