function sequence_duplexes_thermo_generator_struct = F_NearestNeighbors_Parser(NN_model_name,parameter_file_canonical,parameter_file_noncanonical)
%  vargibbs -o=mytest -par=P-SL98.par "-seq=d(ACGTTGAATT)"  "-seq=r(ACGUUGAAUU)" -seqsalt=121 -targetsalt=121 -calc=prediction -ct=50 -printflags=gibbs free energy@37 -duplextype=RNA 
% ∆S2 = ∆S1 + 0.368N ln[Na+]2
% N is number of phosphates in duplex divided by 2
% For RNA i dG(2) = dG(1) - 0.1016*N*log(Na(2)/Na(1))  https://pmc.ncbi.nlm.nih.gov/articles/PMC3859436/
% For DNA i dG(2) = dG(1) - 0.114*N*log(Na(2)/Na(1))
% For RNA i dS(2) = dS(1) + 0.3153*N*log(Na(2)/Na(1))
% For DNA i dS(2) = dS(1) + 0.368*N*log(Na(2)/Na(1))
% parameter_file_noncanonical = [];
% parameter_file_canonical = [];
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/AOP-SL96.par';
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/AOP-SL98.par';
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/P-SL04.par';
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/P-SL98.par';
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/P-SL96.par';
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/P-CH12.par';
% %DNA-RNA
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/AOP-DRVH.par';
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/AOP-DRFT.par';
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/AOP-DRLS.par';
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/P-BN21.par';
% parameter_file_noncanonical = 'src/thirdparty/VarGibbs-4.1/AOP-MM-60.par';
% parameter_file_canonical = 'src/thirdparty/VarGibbs-4.1/AOP-OW04-69.par';
bounds = [1 0 -1]';
override_list = {'src/thirdparty/VarGibbs-4.1/P-BN21.par'};
if (~isempty(parameter_file_noncanonical))
NN_noncanonical_opts = detectImportOptions(parameter_file_noncanonical ,'FileType','delimitedtext');
NN_noncanonical_opts.VariableNames = {'Term','Value','Uncertainty'};
NN_noncanonical_opts.VariableTypes = {'char','double','double'};
NN_noncanonical_opts.CommentStyle{1} = '#';
NN_noncanonical_opts.DataLines = [2 Inf];
NN_noncanonical = readtable(parameter_file_noncanonical ,NN_noncanonical_opts); 
end
if (~isempty(parameter_file_canonical))
    if (or(contains(parameter_file_canonical,'AOP'),contains(parameter_file_canonical,'BOP')))
NN_canonical_opts = detectImportOptions(parameter_file_canonical,'FileType','delimitedtext','Delimiter',[" ", ' +/- ']);
    else
NN_canonical_opts = detectImportOptions(parameter_file_canonical,'FileType','delimitedtext');
    end 
    if (ismember(parameter_file_canonical,override_list))
NN_canonical_opts = detectImportOptions(parameter_file_canonical,'FileType','delimitedtext','Delimiter',[" ", ' +/- ']);
    end
NN_canonical_opts.VariableNames = {'Term','Value','Uncertainty'};
NN_canonical_opts.VariableTypes = {'char','double','double'};
NN_canonical_opts.CommentStyle{1} = '#';
NN_canonical_opts.DataLines = [2 Inf];
NN_canonical = readtable(parameter_file_canonical,NN_canonical_opts); 
end
if (and(~isempty(parameter_file_noncanonical),~isempty(parameter_file_canonical)))
NN_Parameters = [NN_noncanonical(:,{'Term','Value','Uncertainty'}); NN_canonical(:,{'Term','Value','Uncertainty'})];
elseif (and(isempty(parameter_file_noncanonical),~isempty(parameter_file_canonical)))
NN_Parameters = NN_canonical(:,{'Term','Value','Uncertainty'});
elseif (and(~isempty(parameter_file_noncanonical),isempty(parameter_file_canonical)))
NN_Parameters = NN_noncanonical(:,{'Term','Value','Uncertainty'});
elseif (and(isempty(parameter_file_noncanonical),isempty(parameter_file_canonical)))
    dG = NaN;
    return;
    fprintf('No Input parameter Files were specified');
    fprintf('\n')
    fprintf('\n')
end
check_parameters = {'initiation','initiation_CG','initiation_AT','terminal_5TA3','terminal_AU','terminal_AT','terminal_CG','symmetry_correction',...
    'terminal_dArU','terminal_dTrA','terminal_dCrG','terminal_dGrC','Terminal_dCrG_dGrC','Terminal_dArU_dTrA_only'};
NN_Parameters.Value(isnan(NN_Parameters.Value))=0;
NN_Parameters.Uncertainty(isnan(NN_Parameters.Uncertainty))=0;


R = 1.9872;%cal/K mol
if (sum(contains(NN_Parameters.Term,':concentration'))>0)
ReferenceSaltConcentration = NN_Parameters.Value(find(contains(NN_Parameters.Term,':concentration'),1))/1000;
else
ReferenceSaltConcentration = NaN;    
end
Parameters_H = NN_Parameters(contains(NN_Parameters.Term,'enthalpy'),:);
Parameters_S = NN_Parameters(contains(NN_Parameters.Term,'entropy'),:);
Parameters_H_NonNN = Parameters_H(~contains(lower(Parameters_H.Term),':'),:);
Parameters_S_NonNN = Parameters_S(~contains(lower(Parameters_S.Term),':'),:);
Parameters_H_NonNN.Term = extractBefore(Parameters_H_NonNN.Term,'_enthalpy');
Parameters_S_NonNN.Term = extractBefore(Parameters_S_NonNN.Term,'_entropy');
for n = 1:length(check_parameters)
    if (sum(strcmp(Parameters_H_NonNN.Term,check_parameters{n}))==0)
        Parameters_H_NonNN =  vertcat(Parameters_H_NonNN,table(check_parameters(n),0,0,'VariableNames',{'Term','Value','Uncertainty'}));
    end
    if (sum(strcmp(Parameters_S_NonNN.Term,check_parameters{n}))==0)
        Parameters_S_NonNN =  vertcat(Parameters_S_NonNN,table(check_parameters(n),0,0,'VariableNames',{'Term','Value','Uncertainty'}));
    end
end
Parameters_H_NN = Parameters_H(contains(lower(Parameters_H.Term),':'),:);
Parameters_S_NN = Parameters_S(contains(lower(Parameters_S.Term),':'),:);
Parameters_H_NN.Term = extractBefore(Parameters_H_NN.Term,':enthalpy');
Parameters_S_NN.Term = extractBefore(Parameters_S_NN.Term,':entropy');
Parameters_H_NN = CATnWrapper(arrayfun(@(n) table(split(Parameters_H_NN.Term{n},':'),Parameters_H_NN.Value(n)*ones(length(split(Parameters_H_NN.Term{n},':')),1),Parameters_H_NN.Uncertainty(n)*ones(length(split(Parameters_H_NN.Term{n},':')),1),'VariableNames',{'Term','Value','Uncertainty'}),1:length(Parameters_H_NN.Term),'Un',0),1);
Parameters_S_NN = CATnWrapper(arrayfun(@(n) table(split(Parameters_S_NN.Term{n},':'),Parameters_S_NN.Value(n)*ones(length(split(Parameters_S_NN.Term{n},':')),1),Parameters_S_NN.Uncertainty(n)*ones(length(split(Parameters_S_NN.Term{n},':')),1),'VariableNames',{'Term','Value','Uncertainty'}),1:length(Parameters_S_NN.Term),'Un',0),1);
Parameters_H_NN_without_lowercase_Terms = regexprep(Parameters_H_NN.Term, '[a-z]', '');
Parameters_S_NN_without_lowercase_Terms =regexprep(Parameters_S_NN.Term, '[a-z]', '');
if (~isequal(Parameters_H_NN.Term,Parameters_H_NN_without_lowercase_Terms))
Parameters_H_NN_allConfigs = Parameters_H_NN;
Parameters_H_NN_allConfigs.Term = Parameters_H_NN_without_lowercase_Terms;
else
Parameters_H_NN_Flipped = Parameters_H_NN;
Parameters_H_NN_Flipped(:,'Term') = cell2table(cellfun(@(n) strjoin(flip(cellfun(@seqreverse,strsplit(n,'_'),'Un',0)),'_'),table2cell(Parameters_H_NN(:,'Term')),'Un',0));
Parameters_H_NN_allConfigs = unique([Parameters_H_NN;Parameters_H_NN_Flipped],'rows');
end
if (~isequal(Parameters_H_NN.Term,Parameters_H_NN_without_lowercase_Terms))
Parameters_S_NN_allConfigs = Parameters_S_NN;
Parameters_S_NN_allConfigs.Term = Parameters_S_NN_without_lowercase_Terms;
else
Parameters_S_NN_Flipped = Parameters_S_NN;
Parameters_S_NN_Flipped(:,'Term') = cell2table(cellfun(@(n) strjoin(flip(cellfun(@seqreverse,strsplit(n,'_'),'Un',0)),'_'),table2cell(Parameters_S_NN(:,'Term')),'Un',0));
Parameters_S_NN_allConfigs = unique([Parameters_S_NN;Parameters_S_NN_Flipped],'rows');
end
Parameters_H_NN_allConfigs = sortrows(Parameters_H_NN_allConfigs,"Term");
Parameters_S_NN_allConfigs = sortrows(Parameters_S_NN_allConfigs,"Term");
Parameters_NN_allConfig_TermDictionary = dictionary(string(Parameters_S_NN_allConfigs.Term)',1:size(Parameters_S_NN_allConfigs,1));



Sequence_Duplexes = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) arrayfun(@(x) strcat(seqrcomplement(Alignment_Probe_Sequences{x})',seqreverse(Alignment_Target_Sequences{x})')',Sets,'Un',0);
Sequence_Duplexes_Parameterized_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(x) arrayfun(@(n) strcat(x(:,n)','_',x(:,n+1)'),1:size(x,2)-1,'Un',0)', Sequence_Duplexes(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets),'Un',0);
Sequence_Duplexes_BasePair_Groups = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) n(~contains(n,'N')),Sequence_Duplexes_Parameterized_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) ,'Un',0);
Sequence_Duplexes_Terminal_BasePair_Groups = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) {n{1} n{end}},Sequence_Duplexes_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets),'Un',0);
Sequence_Duplexes_contains_CG_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(x) max(contains(x,'CG')),Sequence_Duplexes_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_has_only_AT_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(x) double(sum(ismember(x,{'AT_AT','AT_TA','TA_AT','TA_TA'}))== length(x)),Sequence_Duplexes_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_has_only_AU_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(x) double(sum(ismember(x,{'AU_AU','AU_UA','UA_AU','UA_UA'}))== length(x)),Sequence_Duplexes_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_NumberOfTerminal_CG_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) sum(contains({extractBefore(n{1},'_') extractAfter(n{2},'_')},'CG')),Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_NumberOfTerminal_AT_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) sum(contains({extractBefore(n{1},'_') extractAfter(n{2},'_')},'AT')),Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_NumberOfTerminal_5TA3_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) contains({extractBefore(n{1},'_')},'TA')+ contains({extractAfter(n{2},'_')},'AT'),Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_NumberOfTerminal_AU_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) sum(contains({extractBefore(n{1},'_') extractAfter(n{2},'_')},'AU')),Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_NumberOfTerminal_dArU_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) sum(contains({extractBefore(n{1},'_') extractAfter(n{2},'_')},'AU')),Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_NumberOfTerminal_dTrA_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) sum(contains({extractBefore(n{1},'_') extractAfter(n{2},'_')},'TA')),Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_NumberOfTerminal_dCrG_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) sum(contains({extractBefore(n{1},'_') extractAfter(n{2},'_')},'CG')),Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_NumberOfTerminal_dGrC_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) sum(contains({extractBefore(n{1},'_') extractAfter(n{2},'_')},'GC')),Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_contains_Terminal_dCrG_or_dGrC_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) max(or(contains({extractBefore(n{1},'_') extractAfter(n{2},'_')},'CG'),contains({extractBefore(n{1},'_') extractAfter(n{2},'_')},'GC'))),Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_contains_only_Terminal_dTrA_or_dArU_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(n) and(or(contains({extractBefore(n{1},'_')},'AU'),contains({extractBefore(n{1},'_')},'TA')),or(contains({extractAfter(n{2},'_')},'AU'),contains({extractAfter(n{2},'_')},'TA'))),Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
Sequence_Duplexes_IsComplement = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) arrayfun(@(x) isequal(seqrcomplement(Alignment_Probe_Sequences{x}),seqcomplement(seqreverse(Alignment_Target_Sequences{x}))),1:length(Sets));
Sequence_Duplexes_Features = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) ...
                                                [Sequence_Duplexes_contains_CG_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);...
                                                max([Sequence_Duplexes_has_only_AT_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets); ...
                                                Sequence_Duplexes_has_only_AU_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)],[],1);... 
                                                Sequence_Duplexes_NumberOfTerminal_CG_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);...
                                                Sequence_Duplexes_NumberOfTerminal_AT_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);...
                                                Sequence_Duplexes_NumberOfTerminal_5TA3_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);...
                                                Sequence_Duplexes_NumberOfTerminal_AU_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);...
                                                Sequence_Duplexes_NumberOfTerminal_dArU_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);...
                                                Sequence_Duplexes_NumberOfTerminal_dTrA_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);...
                                                Sequence_Duplexes_NumberOfTerminal_dCrG_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);...
                                                Sequence_Duplexes_NumberOfTerminal_dGrC_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);...
                                                Sequence_Duplexes_contains_Terminal_dCrG_or_dGrC_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);...
                                                Sequence_Duplexes_contains_only_Terminal_dTrA_or_dArU_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)];


seqs_dH_Symmetry = @(IsSymmetrical) ...
                                               (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'symmetry_correction'))+...
                                               bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'symmetry_correction')))*IsSymmetrical;
seqs_dS_Symmetry = @(IsSymmetrical) ...
                                               (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'symmetry_correction'))+...
                                               bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'symmetry_correction')))*IsSymmetrical;
seqs_dH_Initation = @(Sequence_Duplexes_Features_Matrix) ...
                                               (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'initiation'))+...
                                               bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'initiation')))*ones(size(Sequence_Duplexes_Features_Matrix(1,:)))+...
                                               (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'initiation_CG'))+...
                                               bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'initiation_CG')))*Sequence_Duplexes_Features_Matrix(1,:)+...
                                               (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'initiation_AT'))+...
                                               bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'initiation_AT')))*Sequence_Duplexes_Features_Matrix(2,:) + ...
                                              (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'terminal_CG'))+...
                                              bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'terminal_CG')))*Sequence_Duplexes_Features_Matrix(3,:) + ...
                                              (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'terminal_AT'))+...
                                              bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'terminal_AT')))*Sequence_Duplexes_Features_Matrix(4,:) + ...
                                              (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'terminal_5TA3'))+...
                                              bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'terminal_5TA3')))*Sequence_Duplexes_Features_Matrix(5,:) + ...
                                              (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'terminal_AU'))+...
                                              bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'terminal_AU')))*Sequence_Duplexes_Features_Matrix(6,:) + ...
                                              (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'terminal_dArU'))+...
                                              bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'terminal_dArU')))*Sequence_Duplexes_Features_Matrix(7,:) + ...
                                              (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'terminal_dTrA'))+...
                                              bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'terminal_dTrA')))*Sequence_Duplexes_Features_Matrix(8,:) + ...
                                              (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'terminal_dCrG'))+...
                                              bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'terminal_dCrG')))*Sequence_Duplexes_Features_Matrix(9,:) + ...
                                              (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'terminal_dGrC'))+...
                                              bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'terminal_dGrC')))*Sequence_Duplexes_Features_Matrix(10,:) + ...
                                              (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'Terminal_dCrG_dGrC'))+...
                                              bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'terminal_dGrC')))*Sequence_Duplexes_Features_Matrix(11,:) + ...
                                              (Parameters_H_NonNN.Value(strcmp(Parameters_H_NonNN.Term,'Terminal_dArU_dTrA_only'))+...
                                              bounds*Parameters_H_NonNN.Uncertainty(strcmp(Parameters_H_NonNN.Term,'Terminal_dArU_dTrA_only')))*Sequence_Duplexes_Features_Matrix(12,:);

seqs_dS_Initation = @(Sequence_Duplexes_Features_Matrix) ...
                                               (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'initiation'))+...
                                               bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'initiation')))*ones(size(Sequence_Duplexes_Features_Matrix(1,:)))+...
                                               (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'initiation_CG'))+...
                                               bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'initiation_CG')))*Sequence_Duplexes_Features_Matrix(1,:)+...
                                               (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'initiation_AT'))+...
                                               bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'initiation_AT')))*Sequence_Duplexes_Features_Matrix(2,:) + ...
                                              (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'terminal_CG'))+...
                                              bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'terminal_CG')))*Sequence_Duplexes_Features_Matrix(3,:) + ...
                                              (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'terminal_AT'))+...
                                              bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'terminal_AT')))*Sequence_Duplexes_Features_Matrix(4,:) + ...
                                              (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'terminal_5TA3'))+...
                                              bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'terminal_5TA3')))*Sequence_Duplexes_Features_Matrix(5,:) + ...
                                              (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'terminal_AU'))+...
                                              bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'terminal_AU')))*Sequence_Duplexes_Features_Matrix(6,:) + ...
                                              (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'terminal_dArU'))+...
                                              bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'terminal_dArU')))*Sequence_Duplexes_Features_Matrix(7,:) + ...
                                              (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'terminal_dTrA'))+...
                                              bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'terminal_dTrA')))*Sequence_Duplexes_Features_Matrix(8,:) + ...
                                              (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'terminal_dCrG'))+...
                                              bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'terminal_dCrG')))*Sequence_Duplexes_Features_Matrix(9,:) + ...
                                              (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'terminal_dGrC'))+...
                                              bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'terminal_dGrC')))*Sequence_Duplexes_Features_Matrix(10,:) + ...
                                              (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'Terminal_dCrG_dGrC'))+...
                                              bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'terminal_dGrC')))*Sequence_Duplexes_Features_Matrix(11,:) + ...
                                              (Parameters_S_NonNN.Value(strcmp(Parameters_S_NonNN.Term,'Terminal_dArU_dTrA_only'))+...
                                              bounds*Parameters_S_NonNN.Uncertainty(strcmp(Parameters_S_NonNN.Term,'Terminal_dArU_dTrA_only')))*Sequence_Duplexes_Features_Matrix(12,:);
NN_Count_Vector = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cell2mat(cellfun(@(x) reshape(histcounts(categorical(x),categorical(keys(Parameters_NN_allConfig_TermDictionary))),[],1),Sequence_Duplexes_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets),'Un',0))';
Num_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) cellfun(@(x) sum(histcounts(categorical(x),categorical(keys(Parameters_NN_allConfig_TermDictionary)))),Sequence_Duplexes_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets));
seqs_dH_NN = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) sum(permute(repmat(Parameters_H_NN_allConfigs.Value+bounds'.*Parameters_H_NN_allConfigs.Uncertainty,[1 1 length(Sets)]),[2 3 1]).*permute(repmat(NN_Count_Vector(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets),[1 1 length(bounds)]),[3 1 2]),3);
seqs_dS_NN = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) sum(permute(repmat(Parameters_S_NN_allConfigs.Value+bounds'.*Parameters_S_NN_allConfigs.Uncertainty,[1 1 length(Sets)]),[2 3 1]).*permute(repmat(NN_Count_Vector(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets),[1 1 length(bounds)]),[3 1 2]),3);

Sequence_Duplexes_dH = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) ...
                         seqs_dH_Symmetry(Sequence_Duplexes_IsComplement(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)) + ...
                         seqs_dH_Initation(Sequence_Duplexes_Features(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets))+...
                         seqs_dH_NN(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);
Sequence_Duplexes_dS = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) ...
                        seqs_dS_Symmetry(Sequence_Duplexes_IsComplement(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)) + ...
                        seqs_dS_Initation(Sequence_Duplexes_Features(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)) + ...
                        seqs_dS_NN(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);
Sequence_Duplexes_dG = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature) Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) - ((Temperature+273.15)  .* (Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)./1000)); % DeltaG
Sequence_Duplexes_Tm = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,PrimerConc) 1000*Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)./...
                                                 (Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + ...
                                                 R*log(PrimerConc./repmat(reshape((Sequence_Duplexes_IsComplement(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)-2).^2,[],1),[1 length(bounds)])'));

Sequence_DNA_DNA_Duplexes_Salt_Correction_dS_Linear = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) 0.368*Num_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)*log(SaltTarget_Concentration/Salt_NN_ModelReference);
Sequence_DNA_DNA_Duplexes_Salt_Correction_dG_Linear = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) -0.368*(Temperature+273.15)/1000*Num_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)*log(SaltTarget_Concentration/Salt_NN_ModelReference);
Sequence_DNA_DNA_Duplexes_Salt_Corrected_Tm_Linear = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc) 1000*Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)./...
                                                 (Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + Sequence_DNA_DNA_Duplexes_Salt_Correction_dS_Linear(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) +...
                                                 R*log(PrimerConc./repmat(reshape((Sequence_Duplexes_IsComplement(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)-2).^2,[],1),[1 length(bounds)])'));

% Sequence_DNA_DNA_Duplexes_Salt_Correction_dS_Quadratic = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) 0.368*Num_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)*log(SaltTarget_Concentration/Salt_NN_ModelReference);
% Sequence_DNA_DNA_Duplexes_Salt_Correction_dG_Quadratic = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) -0.114*Num_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)*log(SaltTarget_Concentration/Salt_NN_ModelReference);
% Sequence_DNA_DNA_Duplexes_Salt_Corrected_Tm_Quadratic = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc) 1000*Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)./...
%                                                  (Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + Sequence_DNA_DNA_Duplexes_Salt_Correction_dS_Quadratic(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) +...
%                                                  R*log(PrimerConc./repmat(reshape((Sequence_Duplexes_IsComplement(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)-2).^2,[],1),[1 length(bounds)])'));
% 

Sequence_DNA_RNA_Duplexes_Salt_Correction_dS_Linear = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) 0.3276*Num_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)*log(SaltTarget_Concentration/Salt_NN_ModelReference);
Sequence_DNA_RNA_Duplexes_Salt_Correction_dG_Linear = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) -0.3276*(Temperature+273.15)/1000*Num_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)*log(SaltTarget_Concentration/Salt_NN_ModelReference);
Sequence_DNA_RNA_Duplexes_Salt_Corrected_Tm_Linear = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc) 1000*Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)./...
                                                 (Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + Sequence_DNA_RNA_Duplexes_Salt_Correction_dS_Linear(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration)+...
                                                 R*log(PrimerConc./repmat(reshape((Sequence_Duplexes_IsComplement(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)-2).^2,[],1),[1 length(bounds)])'));

% Sequence_DNA_RNA_Duplexes_Salt_Correction_dS_Quadratic = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) (0.324*Fraction_GC_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)-0.468)*log(SaltTarget_Concentration/Salt_NN_ModelReference)+0.133*(log(SaltTarget_Concentration)^2 - log(Salt_NN_ModelReference)^2)
% Sequence_DNA_RNA_Duplexes_Salt_Correction_dG_Quadratic = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) (0.324*Fraction_GC_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)-0.468)*log(SaltTarget_Concentration/Salt_NN_ModelReference)+0.133*(log(SaltTarget_Concentration)^2 - log(Salt_NN_ModelReference)^2)
% Sequence_DNA_RNA_Duplexes_Salt_Corrected_Tm_Quadratic = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc) 1000*Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)./...
%                                                  (Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + Sequence_DNA_RNA_Duplexes_Salt_Correction_dS_Quadratic(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration)+...
%                                                  R*log(PrimerConc./repmat(reshape((Sequence_Duplexes_IsComplement(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)-2).^2,[],1),[1 length(bounds)])'));




parameter_files = {parameter_file_canonical parameter_file_noncanonical};
sequence_duplexes_thermo_generator_struct = struct();
sequence_duplexes_thermo_generator_struct.NN_Model = NN_model_name;
sequence_duplexes_thermo_generator_struct.parameter_files = convertCharsToStrings(parameter_files(~cellfun(@isempty,parameter_files)));
sequence_duplexes_thermo_generator_struct.Salt_NN_ModelReference_Molarity = ReferenceSaltConcentration; 
sequence_duplexes_thermo_generator_struct.State_Variables = {'dH','dS','dG','Tm'};
sequence_duplexes_thermo_generator_struct.States{1} =@(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets); 
sequence_duplexes_thermo_generator_struct.States{2} =@(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets); 
sequence_duplexes_thermo_generator_struct.States{3} =@(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature) Sequence_Duplexes_dG(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature); 
sequence_duplexes_thermo_generator_struct.States{4} =@(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) Sequence_Duplexes_dTm(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets); 
sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Linear_DNA_DNA{1} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) ...
                                                                                                                    Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + 0*SaltTarget_Concentration*Salt_NN_ModelReference;
sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Linear_DNA_DNA{2} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) ....
                                                                                                                    Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + ...
                                                                                                                    Sequence_DNA_DNA_Duplexes_Salt_Correction_dS_Linear(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration);
sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Linear_DNA_DNA{3} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) ....
                                                                                                                    Sequence_Duplexes_dG(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature) + ...
                                                                                                                    Sequence_DNA_DNA_Duplexes_Salt_Correction_dG_Linear(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration);
sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Linear_DNA_DNA{4} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc) ...
                                                                                                                     Sequence_DNA_RNA_Duplexes_Salt_Corrected_Tm_Linear(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc);
sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Linear_DNA_RNA{1} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) ...
                                                                                                                    Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + 0*SaltTarget_Concentration*Salt_NN_ModelReference;
sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Linear_DNA_RNA{2} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) ...
                                                                                                                    Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)+ ...
                                                                                                                    Sequence_DNA_RNA_Duplexes_Salt_Correction_dS_Linear(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration);
sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Linear_DNA_RNA{3} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) ...
                                                                                                                    Sequence_Duplexes_dG(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature)+...
                                                                                                                    Sequence_DNA_RNA_Duplexes_Salt_Correction_dG_Linear(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration);
sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Linear_DNA_RNA{4} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc) ...
                                                                                                                    Sequence_DNA_RNA_Duplexes_Salt_Corrected_Tm_Linear(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc);
% sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Quadratic_DNA_DNA{1} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Salt_NN_ModelReference,SaltTarget_Concentration) ...
%                                                                                                                     Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + 0*SaltTarget_Concentration*Salt_NN_ModelReference;
% sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Quadratic_DNA_DNA{2} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Salt_NN_ModelReference,SaltTarget_Concentration) ....
%                                                                                                                     Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + ...
%                                                                                                                     Sequence_DNA_DNA_Duplexes_Salt_Correction_dS_Quadratic(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Salt_NN_ModelReference,SaltTarget_Concentration);
% sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Quadratic_DNA_DNA{3} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) ....
%                                                                                                                     Sequence_Duplexes_dG(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature) + ...
%                                                                                                                     Sequence_DNA_DNA_Duplexes_Salt_Correction_dG_Quadratic(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Salt_NN_ModelReference,SaltTarget_Concentration);
% sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Quadratic_DNA_DNA{4} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc) ...
%                                                                                                                      Sequence_DNA_RNA_Duplexes_Salt_Corrected_Tm_Quadratic(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc);
% sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Quadratic_DNA_RNA{1} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Salt_NN_ModelReference,SaltTarget_Concentration) ...
%                                                                                                                     Sequence_Duplexes_dH(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) + 0*SaltTarget_Concentration*Salt_NN_ModelReference;
% sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Quadratic_DNA_RNA{2} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Salt_NN_ModelReference,SaltTarget_Concentration) ...
%                                                                                                                     Sequence_Duplexes_dS(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets)+ ...
%                                                                                                                     Sequence_DNA_RNA_Duplexes_Salt_Correction_dS_Quadratic(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration);
% sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Quadratic_DNA_RNA{3} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration) ...
%                                                                                                                     Sequence_Duplexes_dG(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature)+...
%                                                                                                                     Sequence_DNA_RNA_Duplexes_Salt_Correction_dG_Quadratic(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration);
% sequence_duplexes_thermo_generator_struct.States_Salt_Corrected.Quadratic_DNA_RNA{4} = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc) ...
%                                                                                                                     Sequence_DNA_RNA_Duplexes_Salt_Corrected_Tm_Quadratic(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets,Temperature,Salt_NN_ModelReference,SaltTarget_Concentration,PrimerConc);
sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dH = Sequence_Duplexes_dH;
sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dS = Sequence_Duplexes_dS;
sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dG = Sequence_Duplexes_dG;
sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_Tm = Sequence_Duplexes_Tm;
sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_Tm_SaltCorrected.Linear_DNA_DNA = Sequence_DNA_DNA_Duplexes_Salt_Corrected_Tm_Linear;
sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_Tm_SaltCorrected.Linear_DNA_RNA = Sequence_DNA_RNA_Duplexes_Salt_Corrected_Tm_Linear;
sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dS_SaltCorrection_Term.Linear_DNA_DNA= Sequence_DNA_DNA_Duplexes_Salt_Correction_dS_Linear; 
sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dS_SaltCorrection_Term.Linear_DNA_RNA = Sequence_DNA_RNA_Duplexes_Salt_Correction_dS_Linear; 
sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dG_SaltCorrection_Term.Linear_DNA_DNA = Sequence_DNA_DNA_Duplexes_Salt_Correction_dG_Linear; 
sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dG_SaltCorrection_Term.Linear_DNA_RNA = Sequence_DNA_RNA_Duplexes_Salt_Correction_dG_Linear; 
% sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_Tm_SaltCorrected.Quadratic_DNA_DNA = Sequence_DNA_DNA_Duplexes_Salt_Corrected_Tm_Quadratic;
% sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_Tm_SaltCorrected.Quadratic_DNA_RNA = Sequence_DNA_RNA_Duplexes_Salt_Corrected_Tm_Quadratic;
% sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dS_SaltCorrection_Term.Quadratic_DNA_DNA= Sequence_DNA_DNA_Duplexes_Salt_Correction_dS_Quadratic; 
% sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dS_SaltCorrection_Term.Quadratic_DNA_RNA = Sequence_DNA_RNA_Duplexes_Salt_Correction_dS_Quadratic; 
% sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dS_SaltCorrection_Term.Quadratic_DNA_DNA= Sequence_DNA_DNA_Duplexes_Salt_Correction_dG_Quadratic; 
% sequence_duplexes_thermo_generator_struct.Sequence_Duplexes_dS_SaltCorrection_Term.Quadratic_DNA_RNA = Sequence_DNA_RNA_Duplexes_Salt_Correction_dG_Quadratic; 
sequence_duplexes_thermo_generator_struct.debug.NN_Count_Vector = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) NN_Count_Vector(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets);
sequence_duplexes_thermo_generator_struct.debug.Sequence_Duplexes = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) Sequence_Duplexes(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets); 
sequence_duplexes_thermo_generator_struct.debug.Sequence_Duplexes_Parameterized_BasePairs = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) Sequence_Duplexes_Parameterized_BasePairs(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets); 
sequence_duplexes_thermo_generator_struct.debug.Sequence_Duplexes_BasePair_Groups = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) Sequence_Duplexes_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets); 
sequence_duplexes_thermo_generator_struct.debug.Sequence_Duplexes_Terminal_BasePair_Groups = @(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets) Sequence_Duplexes_Terminal_BasePair_Groups(Alignment_Probe_Sequences,Alignment_Target_Sequences,Sets); 
sequence_duplexes_thermo_generator_struct.parameters.Enthalpy.NN = Parameters_H_NN;
sequence_duplexes_thermo_generator_struct.parameters.Enthalpy.NonNN = Parameters_H_NonNN;
sequence_duplexes_thermo_generator_struct.parameters.Entropy.NN = Parameters_S_NN;
sequence_duplexes_thermo_generator_struct.parameters.Entropy.NonNN = Parameters_S_NonNN;
end